<a href="https://colab.research.google.com/github/skyezzzhang/machineintelligence/blob/master/Exercise%2010%20-%20Vectors%20and%20Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Linear Algebra

## Vectors

#### Representing vectors in Python

$$\vec{a}=\begin{bmatrix} 3\\4\end{bmatrix}; \quad
\vec{b}=\begin{bmatrix} 2\\-1\end{bmatrix}; \quad
\vec{c}=\begin{bmatrix} -3\\-3\end{bmatrix}; \quad
\vec{d}=\begin{bmatrix} -2\\3\end{bmatrix}; \quad
\vec{e}=\begin{bmatrix} 2\\3\\5\end{bmatrix}
$$

Import `numpy` library

In [1]:
import numpy as np

By using the numpy *arrays*, represent the vectors $\vec{a}$ to $\vec{e}$

In [2]:
a = np.array([[3], [4]])

b = np.array([[2], [-1]])

c = np.array([[-3], [-3]])

d = np.array([[-2], [3]])

e = np.array([[2], [3], [5]])

Print the values of some of the vectors to make sure they match the definition:

In [3]:
print(e)

[[2]
 [3]
 [5]]


Use NumPy's built-in function `linalg.norm` to compute the length of the vectors $\vec{a}$ and $\vec{e}$:

In [4]:
np.linalg.norm(e)

6.164414002968976

### Vector Operations

##### Adding, subtracting and multiplying vectors by using code

Add the vectors $\vec{a}$ and $\vec{b}$:

In [5]:
a+b

array([[5],
       [3]])

Print the result of the addition:

In [6]:
print(a+b)

[[5]
 [3]]


Subtract vector $\vec{b}$ from $\vec{a}$:

In [7]:
a-b

array([[1],
       [5]])

Multiply the vector $\vec{a}$ by some number (scalar):

In [9]:
2*a

array([[6],
       [8]])

##### Multiplying vectors elementwise

Multiply vectors $\vec{a}$ and $\vec{b}$ elementwise:

In [10]:
a*b

array([[ 6],
       [-4]])

##### Computing the dot product by using code

Compute the dot product of $\vec{a}$ and $\vec{b}$ by multipling two vectors elementwise and summing the multiples. For summing, use the NumPy function `np.sum`:

In [13]:
np.sum(a*b)

2

Apply the last operaton to compute the length of the vector $\vec{a}$ instead of using the function `linalg.norm`:

In [18]:
np.sqrt(np.sum(e*e))

6.164414002968976

## Matrices

This is part of a broader convention of orderly arranging numbers in a rectangular, table-like structure called a __matrix__. A variable containing a vector is represented with a small letter and an arrow above it. A variable containing a matrix is conventionally represented with a capital letter. For example, M is a matrix containing 12 numbers arranged in a particular way.

$$M_{3\times4}=\underset{\;\\\mathbf{3 \, rows \, \times \, 4 \, \text{columns}}}{\begin{bmatrix} 1 & 3 & -2 & 4\\2 & 3 & -1 & -1\\ -1 & 1 & 3 & 4\end{bmatrix}}$$

### Elementary Matrix Operations in Python

Let us define matrices $A$, $B$ and $C$ as follows:

$$
A=\begin{bmatrix}
4 & 2 & -1 & 5 \\
2 & 1 & 3 & -3 \\
-2 & -3 & 1 & 4 \\
\end{bmatrix}; \quad
B=\begin{bmatrix}
-1 & 1 \\
3 & -3 \\
4 & -2 \\
5 & 5 \\
\end{bmatrix}; \quad
C=\begin{bmatrix}
1 & 3  \\
3 & -1 \\
\end{bmatrix}; \quad
D=\begin{bmatrix}
2 & 1  \\
-1 & 2 \\
\end{bmatrix}
$$

Use NumPy's data structure called array to represent matrix A:

Here, we defined the other matrices:

In [ ]:
B = np.array([[-1,  1],
              [ 3, -3],
              [ 4, -2],
              [ 5,  5]])

In [ ]:
C = np.array([[-1,  3],
              [ 3, -1]])

In [ ]:
D = np.array([[ 2, 1],
              [-1, 2]])

Print the variables containing the matrices to make sure they match the definition:

#### Matrix Addition and Subtraction in Python

Add matrices $A$ and $B$ and analyse the result:

Add the matrices $C$ and $D$:

Add the matrix $A$ to itself:

#### Multiplying a Matrix by a Scalar in Python

Multiply the matrix $A$ by 5:

Multiply the matrix $A$ by -5:

#### Matrix Multiplication in Python

Compute the matrix product $A\times B$, by using the NumPy command `np.dot`, and analyse the result:

Compute the matrix product $B\times A$, and analyse the result:

Compute the matrix products $B\times C$ and $B\times D$:

Computing matrix products $C\times D$ and $D\times C$, and analyse the result: